version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "rustlam"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-19ihe2k8l4tto"
s3_prefix = "rustlam"
region = "ap-southeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
